#!/bin/bash

for x in dists/*; do
    dist=$(basename $x)
    echo updating $dist
    mkdir -p $x/main
    dpkg-scanpackages --multiversion pool/$dist/main > $x/main/Packages
    xz -k -f $x/main/Packages
    apt-ftparchive release $x > $x/Release
    gpg --default-key veggiemike -abs -o - $x/Release > $x/Release.gpg
    gpg --default-key veggiemike --clearsign -o - $x/Release > $x/InRelease
done
