#!/bin/bash

pushd dists
for dist in *; do
    mkdir -p $dist/main
    dpkg-scanpackages --multiversion ../pool/$dist/main | sed 's|^Filename: [./]*pool|Filename: pool|' > $dist/main/Packages
    xz -k $dist/main/Packages
done
popd
